### ISSUE TITLE
Cannot deploy using `emptyDir` as local cache

### ISSUE THREAD

**Issue by Darkness4** [CloudVE/galaxy-cvmfs-csi-helm#14]
Hello,
We cannot deploy the driver if we disable both cache.

```
$ helm upgrade --install -n csi-driver-cvmfs -f values.yaml --version 1.6.0 csi-driver-cvmfs cloudve/galaxy-cvmfs-csi
failed to create resource: DaemonSet.apps "csi-cvmfsplugin" is invalid: spec.template.spec.containers[1].volumeMounts[14].name: Not found: "cvmfs-local-cache"
```

Cause:
https://github.com/CloudVE/galaxy-cvmfs-csi-helm/blob/224a2f0fb79fca9d8e03f4c7aa7d55d5d46bc852/galaxy-cvmfs-csi/templates/csi-cvmfsplugin.yaml#L139

The name of the volume should be `cvmfs-local-cache`.

**Comment by almahmoud** [comment]
Thank you for flagging this, that was indeed an oversight! If you could please verify that the chart from branch `fix-empty-dir` fixes the issue as expected (I made https://github.com/CloudVE/galaxy-cvmfs-csi-helm/pull/15 but have not tested it), then I will merge it. (Also feel free to open the PR with the quick change yourself if you'd prefer the GitHub history to reflect that you caught the issue!)
