### ISSUE TITLE
Can’t deploy separately due to missing pvc

### ISSUE THREAD

**Issue by cyrilcros** [CloudVE/galaxy-cvmfs-csi-helm#7]
Hi, currently the Helm chart cannot be installed separately because it is missing the PVC the cache preload job depends on at this line: https://github.com/CloudVE/galaxy-cvmfs-csi-helm/blob/72619fb58ef3dbebe2d76c5caa8c004d38f44eed/galaxy-cvmfs-csi/templates/cvmfs-preload-job.yaml#L76 Only the alienCache or localCache PVC are in the templates.
That PVC is declared in the galaxy-helm chart....

**Comment by nuwang** [comment]
Isn't that PVC being created here? https://github.com/CloudVE/galaxy-cvmfs-csi-helm/blob/72619fb58ef3dbebe2d76c5caa8c004d38f44eed/galaxy-cvmfs-csi/templates/cvmfs-preload-job.yaml#L8

ping @almahmoud

**Comment by nuwang** [comment]
Also noting that we could potentially perform this inner loop only once: https://github.com/CloudVE/galaxy-cvmfs-csi-helm/blob/72619fb58ef3dbebe2d76c5caa8c004d38f44eed/galaxy-cvmfs-csi/templates/cvmfs-preload-job.yaml#L2

**Comment by almahmoud** [comment]
You are right @nuwang , the PVC for each repository's preload cache job will be defined in that loop, so it should not depend on the Galaxy helm chart.
Also @cyrilcros note that with the latest caching improvements in Galaxy as of 20.09, this caching job is obsolete and we set it to false by default now in our default stack

**Comment by almahmoud** [comment]
And yes, the double loop is less than optimal, but it was the easiest way to think about it when templating back then. Given this is not meant to scale (and especially since we don't use it anymore), optimizing it to use something like picking based on the name directly rather than looping until they match did not seem that important.

**Comment by almahmoud** [comment]
@cyrilcros If you'd like, I could help you debug over Zoom one day to help you get up and running on the k8s stack?

**Comment by cyrilcros** [comment]
@almahmoud thanks for your offer, but I am fine for now with just Galaxy minus the CVMFS part. I have now changed my installation to Galaxy 20.09 version 3.6.0. I am using [Argocd](https://github.com/argoproj/argo-cd) to manage my cluster , config is [here](https://pastebin.com/zbcf7eg7) for galaxy with the Helm values at the bottom. My storage backend is a [Ceph filesystem managed by Rook](https://rook.io/docs/rook/v1.5/ceph-filesystem.html).
The `galaxy-cvmfs-gxy-data-pvc` and `galaxy-cvmfs-gxy-main-pvc` are stuck in pending mode. I am getting errors from the provisioner:
`I1216 15:00:00.217359       1 controller.go:926] provision "bioinfo/galaxy-cvmfs-gxy-main-pvc" class "cvmfs-gxy-main": started`
`E1216 15:00:00.223305       1 controller.go:943] provision "bioinfo/galaxy-cvmfs-gxy-main-pvc" class "cvmfs-gxy-main": unexpected error getting claim reference: selfLink was empty, can't make reference`

**Comment by cyrilcros** [comment]
Hi, I am closing this after solving multiple issues. I deployed the cern version found here: https://github.com/cernops/cvmfs-csi . 

- I switched to Kubernetes 1.20 and needed to change the provisioner image to v2.0.0 since some deprecated features were causing an ‘empty self link’ error.
-  The `provisioner` argument here got deprecated in newer provisioner image. It is used here https://github.com/CloudVE/galaxy-cvmfs-csi-helm/blob/72619fb58ef3dbebe2d76c5caa8c004d38f44eed/galaxy-cvmfs-csi/values.yaml#L167
- See https://github.com/cernops/cvmfs-csi/issues/26. I needed to change the provisioner / driver name to `cvmfsDriver` in the templates.
- `cvmfsDriver` is a bad choice because CSI driver names should be valid dns names. In theory you can drop the CSI attacher component (see here: https://kubernetes-csi.github.io/docs/skip-attach.html), but this isn’t possible with the hard coded value.
